apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ $.Chart.Name }}-backend-secrets"
data:
  {{ range .Files.Lines "backend_env" }}
  {{   if . }}
  {{     $parts := regexSplit "=" . 2 }}
  {{     index $parts 0  }}: {{ index $parts 1 | b64enc }}
  {{   end }}
  {{ end }}
