apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-frontend-service"
  namespace: {{ .Values.namespace }}
  labels:
    service: "{{ .Values.frontend.labels.service }}"
spec:
  ports:
    - port: 80
      name: frontend
      targetPort: frontend
      protocol: TCP
  selector:
    service: "{{ .Values.frontend.labels.service }}"
